vi mode commands
nushell/reedline pull request #211
Opened 2021-12-25 08:17 UTC by elferherrera

Adds new functionality to vi mode using vi parser

2021-12-25 21:19 UTC, sholderbach requested changes
Unicode issues will cause panics for non-ascii characters

2021-12-25 21:19 UTC, sholderbach commented on src/core_editor/line_buffer.rs
> +        if self.offset() + 1 > self.lines.len() {
I think this misses the case of being on the last (potentially multibyte character that can not move any further). But the search might fail already.

2021-12-25 21:19 UTC, sholderbach commented on src/core_editor/line_buffer.rs
> +        search_str.find(*c).map(|index| index + self.offset() + 1)
The `+1` has to be replaced with the `char::len_utf8` for the character starting at offset. `LineBuffer::grapheme_right_index()` finds the next index of a grapheme (potentially wider than the codepoint)

```suggestion

        let search_str = &self.lines[self.grapheme_right_index()..];
        search_str.find(*c).map(|index| index + self.grapheme_right_index())
```

2021-12-25 21:19 UTC, sholderbach commented on src/core_editor/line_buffer.rs
> +            self.insertion_point.offset = index - 1
Bit tricky. 
We have to also make sure that we end up with the cursor on valid graphemes (e.g. Emojis multiple code points for a single column on the display)
```suggestion
            self.insertion_point.offset = index;
            self.insertion_point.offset = self.grapheme_left_index();
```

2021-12-26 09:03 UTC, elferherrera commented
@sholderbach I added your suggestions. Thanks, that helped a lot with characters larger than 1 char. 

There is one issue that I haven't figured. When you are in a multi line edit, something like this
```
let a = {
sentence 1
sentence 2
sentence 3
}
```
if I delete the word sentence with `dw` the word doesnt disappear, but it isnt there any more
I checked the emacs bindings and it as well uses the same edit command (DeleteWord)
Is there something I am missing?

2021-12-26 11:36 UTC, sholderbach approved these changes

2021-12-26 12:20 UTC, sholderbach commented on src/core_editor/line_buffer.rs
> +        search_str.find(*c).map(|index| index + self.offset() + 1)
The second `self.grapheme_right_index()` was missing and causing panics on `f<non-ascii>` moves

2021-12-26 18:08 UTC, sholderbach approved these changes

2021-12-26 18:13 UTC, merged