Let prompts choose to repaint on enter
nushell/reedline pull request #627
Opened 2023-08-23 02:07 UTC by ysthakur

This PR goes towards addressing #348. It adds `fn repaint_on_enter(&self) -> bool` to the `Prompt` trait so that a prompt can choose to be repainted on enter. I figured an option could be added to `$env.config` on the Nushell side to enable a transient prompt. After that, the hooks described in [this issue](https://github.com/nushell/nushell/issues/7843) will hopefully start working.

2023-08-23 02:15 UTC, fdncred commented
If reedline is going to support a transient prompt, which would be totally rad, I'd love to see an example in this repo that shows folks how to make a basic one.

2023-08-23 11:43 UTC, fdncred commented
> Let me know if it'd be better to make a completely separate transient_prompt example (and restore the custom_prompt example).

Yes, another example would be best. It also has to be confirmed that your change doesn't break anything else or the other examples.

2023-08-25 11:53 UTC, fdncred commented
I ran this PR example. I'm not sure what it's supposed to do or how to make it work. I just get this
```
    Finished dev [unoptimized + debuginfo] target(s) in 3.55s
     Running `target/debug/examples/transient_prompt`
Transient prompt demo:
Abort with Ctrl-C or Ctrl-D
(transient_prompt example)>ls
::: a
::: b
::: d
:::
:::
:::
```

2023-08-27 21:04 UTC, sholderbach requested changes
Thanks for giving this a shot and working up an example and doing due diligence on the testing.

From a long term maintenance perspective I think this API is a bit too bug prone and can cause confusion.

2023-08-27 21:04 UTC, sholderbach commented on src/prompt/base.rs
> +    }
Mhh I don't like this as a silently stateful API.

I would prefer this to be explicit. Three ideas that come to mind:

- making this an *explicit* setter, by preferrably having `&mut self` and either a descriptive name or an additional parameter setting the post submit state. Could still have No-Op default impl.
- passing the information that the prompt should take its post submit form directly to the `render_*` methods as a parameter. This has the downside of being a breaking change and increasing the API beginners have to learn
- adding additional `render_post_submit_*` methods that have a default implementation which would just invoke their regular form, but could be overridden by the more complex `Prompt` implementations.

2023-08-29 19:38 UTC, fdncred commented
I was getting ready to object to the `unwrap()` in the engine.rs, but it appears that we have many unwraps in this code base. Seems like we should fix those eventually. (not in this pr, of course).

2023-08-29 19:54 UTC, fdncred commented
Wait a second, now that I look at these unwraps, most of them are in tests, which is fine. I found 10 that are not in tests that we need to fix. @ysthakur, would you mind adding error handling to the one you have in engine.rs? I really don't think we want to continue adding unwraps in our code.

2023-08-29 21:09 UTC, fdncred commented
> there's also a bunch of .expect("todo: error handling")

good point. sounds like something for a followup pr, if anyone is interested. hint hint. 😆

2023-08-31 23:06 UTC, sholderbach commented on src/engine.rs
> +    }
If you can get by with this `fn (mut self, Box<>) -> Self` signature, then I don't think the whole `Arc<Mutex<Box<>>>` is needed, right?

2023-09-12 20:06 UTC, sholderbach commented on src/engine.rs
> +    }
@ysthakur sorry for not getting back to you!

Yes I like the variant with `.take()`. To me that is pretty idiomatic.

2023-09-12 20:34 UTC, sholderbach approved these changes
Thanks for sticking with us!

Let's land this, so the road is clear to figure out the best way to configure this in nushell.

(with https://github.com/nushell/nushell/blob/ba6d8ad2617c2100021d6e3c949c0b9088f2667b/Cargo.toml#L167 you can just `cargo update -p reedline` to get the latest unreleased version for testing)

2023-09-12 20:36 UTC, merged

2023-09-12 20:41 UTC, fdncred commented
Can't wait to see what this looks like in nushell. It should be interesting. Good work @ysthakur!