Move left when exiting insert mode
nushell/reedline pull request #699
Opened 2024-01-04 21:20 UTC by andreistan26

As mentioned in #694 using the `vi` editor mode does not match the behavior of the `vim/vi` CLI editors.

- [x] Move left once we exit insert mode
- [ ] Fix `w/e` like commands.

2024-01-23 14:33 UTC, alexandruradovici requested changes

2024-01-23 14:33 UTC, alexandruradovici commented on src/edit_mode/vi/.mod.rs.swp
Delete this file.

2024-01-24 16:18 UTC, andreistan26 commented on src/edit_mode/vi/.mod.rs.swp
Ops, didn't mean that. Thanks!

2024-02-09 12:32 UTC, fdncred commented
Does the second checkbox mean this PR is not finished?

2024-02-09 20:02 UTC, andreistan26 commented
Updated, will stay as it is

2024-02-09 20:08 UTC, fdncred commented
@stormasm I don't use vi mode. Any thoughts on this change?

2024-02-09 20:46 UTC, stormasm commented
@andreistan26 can you please make sure the code you are changing still works fine with all of the latest changes that we have landed in Reedline recently ?  In other words merge your code back into the latest main so we can have the CI run again.  And test your code to make sure it works as you think it should....

Thank you !

2024-02-09 21:15 UTC, andreistan26 commented
Rebased and tested

2024-02-09 21:53 UTC, merged

2024-02-09 21:54 UTC, stormasm commented
@andreistan26 Thank you for checking the code one more time prior to us landing...
have a nice weekend 😄