Add PWD to the `Reedline` state
nushell/reedline pull request #796
Opened 2024-05-31 20:24 UTC by YizhePKU

This PR adds the current working directory as part of the `Reedline` state, instead of using `std::env::current_dir()` to retrieve it from the environment. Applications should call `Reedline::with_cwd()` to update the current working directory when it changes.

This is necessary to support https://github.com/nushell/nushell/pull/12922, which causes `std::env::current_dir()` to deviate from Nushell's `$env.PWD`.

2024-06-13 02:36 UTC, devyn commented
It would probably be best that it's either required or defaults to the actual current dir. Reedline is intended to be useful for more than just nushell

2024-06-14 07:44 UTC, devyn requested changes

2024-06-14 07:44 UTC, devyn commented on src/engine.rs
> +            cwd: "".to_string(),
Just to make it clear - I don't think an empty string should be the default. I think making it an `Option` and then grabbing process working directory if it's `None` is probably the best way to go

2024-06-18 15:36 UTC, YizhePKU commented
> Just to make it clear - I don't think an empty string should be the default. I think making it an Option and then grabbing process working directory if it's None is probably the best way to go.

So you're saying that if `cwd` is set to None, we fallback to the old behavior (calling `std::env::current_dir()`), so that we don't break existing code that doesn't require special PWD logic?

That sounds good. I'll work on it.

2024-06-19 04:43 UTC, devyn commented
Yeah, exactly. Thanks!

2024-06-29 21:19 UTC, fdncred commented
@YizhePKU Do you have any more time to work on this in regards to @devyn's comments?

2024-07-03 17:40 UTC, YizhePKU commented
I think this will do? I'll update the other PR if this gets merged.

2024-07-03 19:02 UTC, fdncred commented
Thanks @YizhePKU! We appreciate you coming back around to this PR. @devyn, when you get a chance can you please look at this. I'd like to get it landed if possible.

2024-07-05 20:47 UTC, devyn approved these changes

2024-07-05 20:47 UTC, devyn commented
Looks correct to me. Thanks!

2024-07-05 20:47 UTC, merged

2024-12-21 20:58 UTC, jakeswenson commented
Does anyone know how this relates to nushell/nushell/issues/5799? Not sure if this directly resolves it or if there is more work to be done?